### ISSUE TITLE
Running do_scan.py in a jail

### ISSUE THREAD

**Issue by mgerstner** [openSUSE/obs-service-cargo_audit#3]
`do_scan.py` executes client side services from a large number of OBS packages. While we sure don't hope that packages in Factory contain malicious configurations it could be prudent anyway to execute these services only in a restricted environment using a tool like `nsjail`, especially to prevent writes outside of the package directory and maybe also prevent reading from the current users home directory.

Using this feature could be made optional for people that don't have the necessary components installed (only print a warning then or something alike).

**Comment by Firstyear** [comment]
Thanks @mgerstner I've updated main with the fixes for do_scan to run all the osc service commands in nsjail :)
